[package]
name = "kepler"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2018"
license = "Apache-2.0"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
anyhow = "1.0"
didkit = { path = "../didkit/lib" }
ssi = { path = "../ssi" }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
nom = "6"
bs58 = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
hex = "0.4"
tokio-stream = { version = "0.1", features = ["fs"] }
cached = "0.23"
base64 = "0.13"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
tracing = "0.1"
bincode = "1.3"
sled = "0.34"
async-recursion = "0.3"
libipld = "0.12"

async-global-executor = { version = "2.0.2", optional = true }
async-io = "1.6.0"
async-trait = "0.1.50"
fnv = "1.0.7"
futures = "0.3.15"
ipfs-sqlite-block-store = "0.6.1"
lazy_static = "1.4.0"
libp2p-bitswap = "0.19.0"
libp2p-broadcast = "0.5.0"
names = "0.11.0"
parking_lot = "0.11.1"
pin-project = "1.0.7"
prometheus = "0.12.0"
thiserror = "1.0.26"
void = "1.0.2"

[dependencies.libp2p]
version = "0.39.1"
default-features = false
features = [
    "gossipsub",
    "identify",
    "kad",
    "ping",
    "relay",
    "mplex",
    "noise",
    "pnet",
    "yamux",
    "tcp-tokio",
    "dns-tokio",
]

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
# libipld = { version = "0.12.0", default-features = false, features = ["dag-cbor", "dag-pb", "derive"] }
# libp2p-bitswap = { version = "0.19.0", default-features = false, features = ["compat"] }
multihash = { version = "0.14.0", default-features = false, features = ["blake3"] }
rand = "0.8.4"
tempdir = "0.3.7"
tracing-subscriber = "0.2.19"
