[package]
name = "kepler"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "8d4d0110", features = ["tls"] }
ipfs-embed = "0.19"
anyhow = "1.0"
ssi = "0.2.0"
did-pkh = "0.0.1"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
nom = "6"
bs58 = "0.4"
serde_json = "1"
hex = "0.4"
async-std = "1.9"
libipld = "0.11"
