[package]
name = "kepler"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
multihash = "0.13"
cid = "0.6"
rocksdb = "0.15"
anyhow = "1.0"
ssi = { path = "../ssi" }
did-tezos = { path = "../ssi/did-tezos" }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
nom = "6"
bs58 = "0.4"
serde_json = "1"
hex = "0.4"

