[package]
name = "kepler"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4"
multihash = "0.13"
